### ISSUE TITLE
Application menu shortcut

### ISSUE THREAD

**Issue by ptempier** [flathub/com.airtame.Client#4]
Hello

Is there any problem to add an application menu entry for airtame ?

Can someone more experimented than me and with permissions on this repository can do it ?
(i don't think it's _that_ complex and maybe faster than doing a merge request procedure)

Or should i submit a merge request ?

If that changes anthing, i am fedora and i don't have any airtame entry in the application menu.
But maybe that's a Fedora/cinnamon specific issue.

Pascal

**Comment by klausenbusk** [comment]
Airtame should be in the menu AFAIK, but it is a long time since I used this app. Perhaps @bbhtt can chime in?

**Comment by bbhtt** [comment]
Not sure I don't see any direct issues. I'm on GNOME and while GNOME doesn't have an application menu, it does appear in the overview for me. (With the [application menu extension](https://extensions.gnome.org/extension/6/applications-menu/) it does appear in the Sound and Video category as expected)

@ptempier Is this the only Flatpak app that doesn't appear? Is the `XDG_DATA_DIR` set to export the applications from flatpak locations ie.

```
echo $XDG_DATA_DIRS
/home/user/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

Can you try copying the .desktop file `{/home/user/.local/share, /var/lib}/flatpak/exports/share/applications/com.airtame.Client.desktop` to `~/.local/share/applications` to see if that helps?

**Comment by ptempier** [comment]
In fact the issue isn't linked to this flatpack. The menu entry appears after a session restart.
So i guess it's more a flatpack thing if the menu doesn't get refreshed after the install.

**Comment by bbhtt** [comment]
There is a [script](https://koji.fedoraproject.org/koji/fileinfo?rpmID=33940286&filename=/etc/profile.d/flatpak.sh) `/etc/profile.d/flatpak.sh` that sets the `XDG_DATA_DIR` so that applications in `{/home/user/.local/share, /var/lib}/flatpak/exports/share/applications/` appear in the menu. If you recently installed flatpak, that script wasn't sourced and the variable wasn't set. Restarting the session sources scripts from `/etc/profile.d`.

**Comment by klausenbusk** [comment]
Not related to this flatpak, so closing.
