### ISSUE TITLE
Update client

### ISSUE THREAD

**Issue by AFCMS** [flathub/com.airtame.Client#7]
Currently the app from the Airtame website (v4.10) can work with Wayland (kinda) using portals, but the Flatpak (v4.5) isn't up-to-date and doen't include this quite useful feature.

**Comment by Blackburn29** [comment]
I will try and get a PR up to update this.

**Comment by Blackburn29** [comment]
https://github.com/flathub/com.airtame.Client/pull/8

**Comment by klausenbusk** [comment]
I just reviewed the PR. Do any of you want to become a (co-)maintainer of this flatpak? I haven't used Airtame for years.

**Comment by Blackburn29** [comment]
> I just reviewed the PR. Do any of you want to become a (co-)maintainer of this flatpak? I haven't used Airtame for years.

Yes, that would be great

**Comment by klausenbusk** [comment]
> Yes, that would be great

Issue opened: https://github.com/flathub/flathub/issues/5439.
